# Numpy Arrays

In [1]:
my_list = [1,2,3]

In [3]:
import numpy as np

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [7]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [11]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [12]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [13]:
np.ones((2,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [15]:
np.linspace(0,5,10)

array([ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
        2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ])

In [16]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [17]:
np.random.rand()

0.7675956516012061

In [18]:
np.random.rand(5,5)

array([[ 0.98439151,  0.29105978,  0.81396066,  0.87976467,  0.72614769],
       [ 0.21478379,  0.34346347,  0.79210689,  0.95795374,  0.89142768],
       [ 0.86336322,  0.14773945,  0.67068032,  0.95846702,  0.87100109],
       [ 0.33940752,  0.20190045,  0.82714922,  0.90980658,  0.51013727],
       [ 0.50412634,  0.62934137,  0.30622416,  0.65457508,  0.99366212]])

In [21]:
np.random.randn(3,3)

array([[ 1.6383004 , -0.09641897,  0.227489  ],
       [ 0.52896154,  0.63696456,  0.0735397 ],
       [ 1.95338897, -0.42842097, -0.72012783]])

In [24]:
np.random.randint(1,100,10)

array([98, 22, 77, 70, 77, 25, 48,  1, 91, 25])